version: '3.9'

services:
  crm_db:
    container_name: crm_db
    image: postgres:16
    ports:
      - 5436:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}